config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :tasks do
      member do
        patch :complete
      end
    end
  end
  root 'projects#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :project
  def completed?
    !completed_at.blank?
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :projects
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]
  before_action :authenticate_user!
  def index
    @projects = current_user.projects.all
  end

  def show; end

  def new
    @project = current_user.projects.build
  end

  def edit; end

  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Todo list was successfully destroyed.' }
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description)
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, except: [:create]

  def create
    @task = @project.tasks.create(task_params)
    redirect_to @project
  end

  def destroy
    @task = @project.tasks.find(params[:id])
    if @task.destroy
      flash[:success] = 'Task item was deleted.'
    else
      flash[:error] = 'Task could not be deleted.'
    end
    redirect_to @project
  end

  def complete
    @task.update_attribute(:completed_at, Time.now)
    redirect_to @project, notice: 'Task completed'
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_task
    @task = @project.tasks.find(params[:id])
  end

  def task_params
    params[:task].permit(:content, :deadline)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Todo
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    link[href="http://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet" type="text/css"]
    link[href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet"]
  body
    .container
      - if user_signed_in?
        = link_to 'Sign_out', destroy_user_session_path,
        :style=>'float: right; margin-right: 3em;',
        method: :delete, data: { confirm: "Are you sure?" }
        i style="float:right; margin-right: 1em;"
          = current_user.email
      .user-data style="margin-top:1.5em;"
        = yield

app/views/projects/_form.html.slim
= simple_form_for project, html: { class: 'form-inline' }, local: true do |form|
  - if project.errors.any?
    #error_explanation
      h2
        = pluralize(project.errors.count, "error")
        |  prohibited this project from being saved:
      ul
        - project.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.input :description
  .actions
    = form.submit

app/views/projects/edit.html.slim
h1.project_title
  | Editing Project
.forms
  = render 'form', project: @project
.links
  = link_to 'Cancel', projects_path

app/views/projects/index.html.slim
- @projects.each do |project|
  .index_row.clearfix
    h2.project_title
      = link_to project.title, project
    p.project_sub_title
      = project.description
.links
  = link_to "New Project", new_project_path

app/views/projects/new.html.slim
h1.project_title
  | New Todo List
.forms
  = render 'form', project: @project
.links
  = link_to 'Back', projects_path

app/views/projects/show.html.slim
p#notice
  = notice
h2.project_title
  = @project.title
p.project_sub_title
  = @project.description
#tasks_wrapper
  = render @project.tasks
  #form
    = render "tasks/form"
.links
  = link_to 'Edit', edit_project_path(@project)
  |  |
  = link_to 'Delete', project_path(@project), method: :delete, data: { confirm: "Are you sure?" }
  |  |
  = link_to 'Back', projects_path

app/views/tasks/_form.html.slim
= simple_form_for([@project, @project.tasks.build]) do |f|
  = f.text_field :content, placeholder: "New Task"
  = f.input :deadline, as: :date
  = f.submit

app/views/tasks/_task.html.slim
.row.clearfix
  - if task.completed?
    .complete
      = link_to complete_project_task_path(@project, task.id), method: :patch do
        i.fa.fa-check[style="opacity: 0.4;"]
    .task
      p[style="opacity: 0.4;"]
        strike
          = task.content
    .deadline
      i
        = task.deadline
    .trash
      = link_to project_task_path(@project, task.id), method: :delete, data: { confirm: "Are you sure?" } do
        i.fa.fa-trash
  - else
    .complete
      = link_to complete_project_task_path(@project, task.id), method: :patch do
        i.fa.fa-circle-thin
    .task
      p
        = task.content
    .deadline
      i
        = task.deadline
    .trash
      = link_to project_task_path(@project, task.id), method: :delete, data: { confirm: "Are you sure?" } do
        i.fa.fa-trash